use_frameworks!

def settings
    platform :ios, '11.0'
    # ignore all warnings from all pods
    inhibit_all_warnings!
end

def tests_pods
  pod 'Nimble', '8.0.4'
  pod 'Quick', '2.2.0'
end

target '{{cookiecutter.app_name}}' do
  # Pods for {{cookiecutter.app_name}}
  settings

  pod 'R.swift', '5.2.2'
  pod 'SwiftLint', '0.39.2'
  pod 'SwiftyRedux', '0.3.0'
  pod 'Sourcery', '0.18.0'

  target '{{cookiecutter.app_name}}Tests' do
    inherit! :search_paths
    # Pods for testing
    tests_pods
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
